# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voicebot_pb2 as voicebot__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voicebot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoicebotAiServiceStub(object):
    """통화 세션 중 AI 엔진과 실시간(Real-time)으로 통신하기 위한 양방향 스트리밍 서비스
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSession = channel.stream_stream(
                '/voicebot.ai.VoicebotAiService/StreamSession',
                request_serializer=voicebot__pb2.AudioChunk.SerializeToString,
                response_deserializer=voicebot__pb2.AiResponse.FromString,
                _registered_method=True)


class VoicebotAiServiceServicer(object):
    """통화 세션 중 AI 엔진과 실시간(Real-time)으로 통신하기 위한 양방향 스트리밍 서비스
    """

    def StreamSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoicebotAiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=voicebot__pb2.AudioChunk.FromString,
                    response_serializer=voicebot__pb2.AiResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voicebot.ai.VoicebotAiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voicebot.ai.VoicebotAiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoicebotAiService(object):
    """통화 세션 중 AI 엔진과 실시간(Real-time)으로 통신하기 위한 양방향 스트리밍 서비스
    """

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voicebot.ai.VoicebotAiService/StreamSession',
            voicebot__pb2.AudioChunk.SerializeToString,
            voicebot__pb2.AiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
