# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voicebot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voicebot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evoicebot.proto\x12\x0bvoicebot.ai\"I\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x13\n\x0bis_speaking\x18\x03 \x01(\x08\"\xc0\x01\n\nAiResponse\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.voicebot.ai.AiResponse.ResponseType\x12\x14\n\x0ctext_content\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63lear_buffer\x18\x04 \x01(\x08\">\n\x0cResponseType\x12\x0e\n\nSTT_RESULT\x10\x00\x12\r\n\tTTS_AUDIO\x10\x01\x12\x0f\n\x0b\x45ND_OF_TURN\x10\x02\x32Z\n\x11VoicebotAiService\x12\x45\n\rStreamSession\x12\x17.voicebot.ai.AudioChunk\x1a\x17.voicebot.ai.AiResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voicebot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=31
  _globals['_AUDIOCHUNK']._serialized_end=104
  _globals['_AIRESPONSE']._serialized_start=107
  _globals['_AIRESPONSE']._serialized_end=299
  _globals['_AIRESPONSE_RESPONSETYPE']._serialized_start=237
  _globals['_AIRESPONSE_RESPONSETYPE']._serialized_end=299
  _globals['_VOICEBOTAISERVICE']._serialized_start=301
  _globals['_VOICEBOTAISERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
